### ISSUE TITLE
Almost all IU show "NaN"

### ISSUE THREAD

**Issue by yasuru** [wkentaro/fcn#83]
I'm investigating IU of each class in trained FCN16s. In order to output each IU, I rewrote label_accuracy_score in utils.py as follows ("iu" is added to "return") ; 

------------

def label_accuracy_score(label_true, label_pred, n_class):
    hist = _fast_hist(label_true.flatten(), label_pred.flatten(), n_class)
    acc = np.diag(hist).sum() / hist.sum()
    acc_cls = np.diag(hist) / hist.sum(axis=1)
    acc_cls = np.nanmean(acc_cls)
    iu = np.diag(hist) / (hist.sum(axis=1) + hist.sum(axis=0) - np.diag(hist))
    mean_iu = np.nanmean(iu)
    freq = hist.sum(axis=1) / hist.sum()
    fwavacc = (freq[freq > 0] * iu[freq > 0]).sum()
    return acc, acc_cls, mean_iu, fwavacc, iu

-------------

Then, I outputted iu[0], iu[1], .... ,iu[20].  Hoverer, almost all IU shew "NaN". 
Do you happen to have any knowledge about this cause? If you find out this cause, please tell me.

**Comment by wkentaro** [comment]
It is an expected behavior, because iu must be nan for class labels which does not exist in the ground truth label image.
I added tests in https://github.com/wkentaro/fcn/pull/93, and you may want to try it.

```
python tests/utils_tests/test_label_accuracy_score.py
```

and you can add `print(iu)` in your utils.py to see what happens: https://github.com/wkentaro/fcn/blob/master/fcn/utils.py#L312
